# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
- master
pr:
- master

variables:
  GOPATH: $(Agent.BuildDirectory)/go
  PATH: $(Agent.BuildDirectory)/go/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GOVER: 1.13

jobs:
- job: UnitTest
  pool:
    vmImage: ubuntu-16.04
  dependsOn: []
  timeoutInMinutes: 60
  steps:
  - template: install_deps.yml
  - checkout: self
  # TODO: seperate unit-test and checks.
  # TODO: resolve dependencies between dependencies.sh and install_deps.yml
  - script: make unit-test
    displayName: Run checks and unit test
  - script: gobin -run github.com/axw/gocov/gocov@master convert ./coverage.txt | gobin -run github.com/AlekSi/gocov-xml > ./coverage.xml
    displayName: Convert coverage report to cobertura format
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: ./coverage.xml

- job: IntegrationTest
  pool:
    vmImage: ubuntu-16.04
  dependsOn: []
  timeoutInMinutes: 60
  steps:
  - template: install_deps.yml
  - checkout: self
  - script: make integration-test
    displayName: Run integration test
    env:
      # TODO: update this variable name in the Makefile
      JENKINS_URL: true